oauthUrl: 'https://id.qlteacher.com/api/auth/token?grant_type=password'
client:
  clientId: '#clientId#'
  clientSecret: '#clientSecret#'
  userName: '#userName#'
  userPassword: '#userPassword#'
baseInfo:
  structuresUrl: 'https://api-1s1ksd.qlteacher.com/api/otoel-base-info/activity/structures/'
  loadTeacherUrl: 'https://api-1s1ksd.qlteacher.com/api/otoel-base-info/teacher/'
  queryCatalogInfosPageUrl: 'https://api-1s1ksd.qlteacher.com/api/otoel-base-info/catalog-infos'
lesson:
  schoolId: '#学校编号#'
  teams:
    - userId: '#主持人编号#'
      type: 'master'
    - userId: '#核心成员1编号#'
      type: 'lecturer'
    - userId: '#核心成员2编号#'
      type: 'lecturer'
    - userId: '#普通成员编号#'
      type: 'member'
  applyLessonUrl: 'https://api-1s1ksd.qlteacher.com/api/otoel-upload/lesson/apply'
  submitLessonUrl: 'https://api-1s1ksd.qlteacher.com/api/otoel-upload/lesson/submit'
  loadLessonUrl: 'https://api-1s1ksd.qlteacher.com/api/otoel-upload/lesson/info/'
  updateLessonUrl: 'https://api-1s1ksd.qlteacher.com/api/otoel-upload/lesson/update'
  deleteLessonUrl: 'https://api-1s1ksd.qlteacher.com/api/otoel-upload/lesson/'
  queryLessonsPageUrl: 'https://api-1s1ksd.qlteacher.com/api/otoel-upload/lessons/page'
  lessonCoverUrl: 'https://api-1s1ksd.qlteacher.com/api/otoel-upload/lessons/cover/'
  applyLessonStructureUrl: 'https://api-1s1ksd.qlteacher.com/api/otoel-upload/lessons/structure/'
  commitLessonStructuresUrl: 'https://api-1s1ksd.qlteacher.com/api/otoel-upload/lessons/structures/'
  lessonCheckUrl: 'https://api-1s1ksd.qlteacher.com/api/otoel-upload/lessons/check/'
  lessonConfirmUrl: 'https://api-1s1ksd.qlteacher.com/api/otoel-upload/lessons/confirm/'
